### ISSUE TITLE
Improve Attachment support

### ISSUE THREAD

**Issue by enm10k** [enm10k/nocodb-mobile#19]
## TODO

- [x] Implement a new page to manage attached files
- [ ] Implement a dialog that allows users to view file details and also rename the file there
- [ ] Request permission to notify file download completion on Android (?)

### Prototype

[Screen_recording_20240605_202942.webm](https://github.com/enm10k/nocodb-mobile/assets/17097142/2bb86b00-a869-478c-8f0e-ca5056b543b9)

**Comment by ballinger** [comment]
not sure if i got the latest build (apk's have expired in githubs action tab). i am able to see the upload icon, and choices, redirect to camera or file browser work, once selected or taking a picture it returns to the app but no upload or visual feedback, as if nothing happend.
